---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-6.8
  - name: centos-7.3

suites:
  - name: default
    run_list:
      - recipe[ini_file::default]
      - recipe[ini_file::test]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
